// Generated by Wrangler on Thu Aug 22 2024 21:18:12 GMT-0400 (Eastern Daylight Saving Time)
// by running `wrangler types`

interface Env {
	"ttc-service-alerts": KVNamespace;
	THREADS_ACCESS_TOKEN: string;
	THREADS_USER_ID: string;
}
