// Generated by Wrangler on Wed Jun 19 2024 07:59:21 GMT-0400 (Eastern Daylight Saving Time)
// by running `wrangler types`

interface Env {
	ttc_alerts: KVNamespace;
	THREADS_ACCESS_TOKEN: string;
	THREADS_USER_ID: string;
	DB: D1Database;
}
